// Generated by CoffeeScript 1.3.3
(function() {
  var Ansi, CssPre;

  Ansi = $().jqconsole.Ansi;

  CssPre = 'jqconsole-ansi-';

  describe('Ansi', function() {
    describe('#_style', function() {
      var ansi;
      ansi = null;
      beforeEach(function() {
        return ansi = new Ansi();
      });
      it('applies and replaces font', function() {
        ansi._style('11');
        assert.deepEqual(["" + CssPre + "fonts-1"], ansi.klasses);
        ansi._style('19');
        return assert.deepEqual(["" + CssPre + "fonts-9"], ansi.klasses);
      });
      it('applies and replaces color', function() {
        ansi._style('31');
        assert.deepEqual(["" + CssPre + "color-" + (ansi._color(1))], ansi.klasses);
        ansi._style('37');
        assert.deepEqual(["" + CssPre + "color-" + (ansi._color(7))], ansi.klasses);
        ansi._style('39');
        return assert.deepEqual([], ansi.klasses);
      });
      return it('applies and replaces background-color', function() {
        ansi._style('41');
        assert.deepEqual(["" + CssPre + "background-color-" + (ansi._color(1))], ansi.klasses);
        ansi._style('47');
        assert.deepEqual(["" + CssPre + "background-color-" + (ansi._color(7))], ansi.klasses);
        ansi._style('49');
        return assert.deepEqual([], ansi.klasses);
      });
    });
    return describe('#stylize', function() {
      var ansi;
      ansi = null;
      beforeEach(function() {
        return ansi = new Ansi();
      });
      it('appends a styles', function() {
        var html;
        html = ansi.stylize('test\x1B[1mhello');
        return assert.equal(html, "<span class=\"\">test</span><span class=\"" + CssPre + "bold\">hello</span>");
      });
      it('appends multiple styles', function() {
        var html;
        html = ansi.stylize('test\x1B[1;2mhello');
        return assert.equal(html, "<span class=\"\">test</span><span class=\"" + CssPre + "bold " + CssPre + "lighter\">hello</span>");
      });
      return it('appends multiple styles at different intervals', function() {
        var html;
        html = ansi.stylize('test\x1B[1mhello\x1B[2mhi');
        assert.equal(html, "<span class=\"\">test</span><span class=\"" + CssPre + "bold\">hello</span><span class=\"" + CssPre + "bold " + CssPre + "lighter\">hi</span>");
        html = ansi.stylize('a\x1B[53mb\x1B[21mc\x1B[md');
        return assert.equal(html, "<span class=\"" + CssPre + "bold " + CssPre + "lighter\">a</span><span class=\"" + CssPre + "bold " + CssPre + "lighter " + CssPre + "overline\">b</span><span class=\"" + CssPre + "overline\">c</span><span class=\"\">d</span>");
      });
    });
  });

}).call(this);
