// Generated by CoffeeScript 1.3.3
(function() {

  describe('JQConsole', function() {
    var $container, jqconsole, _ref;
    _ref = jqconsoleSetup(), $container = _ref.$container, jqconsole = _ref.jqconsole;
    return describe('#constructor', function() {
      it('instantiates', function() {
        equal(jqconsole.header, 'header');
        equal(jqconsole.prompt_label_main, 'prompt_label');
        equal(jqconsole.prompt_label_continue, 'prompt_continue');
        equal(jqconsole.indent_width, 2);
        equal(jqconsole.GetState(), 'output');
        deepEqual(jqconsole.input_queue, []);
        deepEqual(jqconsole.history, []);
        ok(jqconsole.$console.length);
        ok(jqconsole.$console instanceof jQuery);
        equal($container.text().trim(), 'header');
        strictEqual($container.data('jqconsole'), jqconsole);
        ok(jqconsole.$prompt.length);
        return ok(jqconsole.$input_source.length);
      });
      return it('setup events', function(done) {
        var counter, fn;
        counter = 0;
        jqconsole.$input_source.focus(function() {
          return counter++;
        });
        jqconsole.$console.mouseup();
        fn = function() {
          ok(counter);
          return done();
        };
        return setTimeout(fn, 10);
      });
    });
  });

}).call(this);
