// Generated by CoffeeScript 1.3.3
(function() {
  var jqconsole;

  jqconsole = jqconsoleSetup().jqconsole;

  describe('Shortcuts', function() {
    describe('#RegisterShortcut', function() {
      it('throws if callback not function', function() {
        return assert.throws(function() {
          return jqconsole.RegisterShortcut('b', 'c');
        });
      });
      it('registers shortcut by string', function() {
        var cb;
        cb = function() {};
        jqconsole.RegisterShortcut('a', cb);
        deepEqual(jqconsole.shortcuts['a'.charCodeAt(0)], [cb]);
        return deepEqual(jqconsole.shortcuts['A'.charCodeAt(0)], [cb]);
      });
      it('registers shortcut by charcode', function() {
        var cb;
        cb = function() {};
        jqconsole.RegisterShortcut('c'.charCodeAt(0), cb);
        deepEqual(jqconsole.shortcuts['c'.charCodeAt(0)], [cb]);
        return deepEqual(jqconsole.shortcuts['C'.charCodeAt(0)], [cb]);
      });
      return it('shortcuts must be ascii', function() {
        return assert.throws(function() {
          return jqconsole.RegisterShortcut('ƒ', function() {});
        });
      });
    });
    return describe('#UnRegisterShortcut', function() {
      it('removes all callback for a shortcut', function() {
        var cb;
        cb = function() {};
        jqconsole.RegisterShortcut('a', cb);
        jqconsole.UnRegisterShortcut('a');
        return deepEqual(jqconsole.shortcuts['a'.charCodeAt(0)], void 0);
      });
      return it('removes specific callback', function() {
        var aCb, bCb;
        aCb = function() {};
        bCb = function() {};
        jqconsole.RegisterShortcut('a', aCb);
        jqconsole.RegisterShortcut('a', bCb);
        jqconsole.UnRegisterShortcut('a', aCb);
        return deepEqual(jqconsole.shortcuts['a'.charCodeAt(0)], [bCb]);
      });
    });
  });

}).call(this);
